name: Deploy lambda function

on:
 push:
  branches:
   - main

jobs:

 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v3
   - name: Install python
     uses: actions/setup-python@v4.5.0
     with:
      python-version: 3.8
   - name: Install libs
     run: |
         echo 'First dir'
         pwd
         ls
         cd functions
         if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
   - name: Create Zip
     run: |
         echo 'Second dir'
         pwd
         cd functions
         zip -r ../${{ github.sha }}.zip .
   - name: Acrchive artifact
     uses: actions/upload-artifact@v2
     with:
      name: zipped-bundle
      path: ${{ github.sha }}.zip
      
 publish:  #remake it because it doesn't work with tocken 
  needs: build
  runs-on: ubuntu-latest
  steps:
   - name: Check what is github.ref
     run: echo ${{ github.ref }}
   - name: create release
     id: create-release
     uses: actions/create-release@v1
     env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
     with:
      tag_name: ${{ github.ref }}
      release_name: ${{ github.ref }}
      body: |
           yay, new release
      draft: false
      prerelease: false
   - name: download artifact
     uses: actions/download-artifact@v2
     with:
      name: zipped-bundle
   - name: upload release assets
     uses: actions/upload-release-asset@v1
     env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
     with:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      asset_path: ./${{ github.sha }}.zip
      name: source_with_libs
      asset_content_type: application\zip
