name: Deploy lambda function

on:
 push:
  branches:
   - main

jobs:

 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v3
   - name: Install python
     uses: actions/setup-python@v4.5.0
     with:
      python-version: 3.8
   - name: Install libs
     run: |
         echo 'First dir'
         pwd
         ls
         cd functions
         if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
   - name: Create Zip
     run: |
         echo 'Second dir'
         pwd
         cd functions
         zip -r ../${{ github.sha }}.zip .
   - name: Acrchive artifact
     uses: actions/upload-artifact@v2
     with:
      name: zipped-bundle
      path: ${{ github.sha }}.zip
      
 publish:
  runs-on: ubuntu-latest
  steps:
   - name: Check what is github.ref
     run: echo ${{ github.ref }}
   - name: publish release
     uses: actions/create-release@v1
     env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
     with:
      tag_name: ${{ github.run_number }}
      release_name: ${{ github.run_number }}
      body: |
           yay, new release
      draft: false
      prerelease: false
      
