name: Deploy lambda function

on:
 push:
  branches:
   - main

jobs:

 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v3
   - name: Install python
     uses: actions/setup-python@v4.5.0
     with:
      python-version: 3.8
   - name: Install libs
     run: |
         echo 'First dir'
         pwd
         ls
         cd functions
         if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
   - name: Create Zip
     run: |
         echo 'Second dir'
         pwd
         cd functions
         zip -r ../${{ github.sha }}.zip .
   - name: Acrchive artifact
     uses: actions/upload-artifact@v2
     with:
      name: zipped-bundle
      path: ${{ github.sha }}.zip
      
 publish:  
 # to work with github_token need right premisions on settings of actions, otherwise use PAT
  needs: build
  runs-on: ubuntu-latest
  steps:
# Check what is github.ref - it refers to HEAD, on which branch it watch
   - name: create release
     id: create-release
     uses: actions/create-release@v1
     env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
     with:
      tag_name: ${{ github.run_number }}
      release_name: ${{ github.run_number }}
      body: |
           yay, new release
      draft: false
      prerelease: false
   - name: download artifact
     uses: actions/download-artifact@v2
     with:
      name: zipped-bundle
   - name: upload release assets
     uses: actions/upload-release-asset@v1
     env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
     with:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      asset_path: ./${{ github.sha }}.zip
      asset_name: source_with_libs.zip
      asset_content_type: application\zip

