name: Deploy release to S3 

on:
  release:
    types: [created]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
     - name: Download release
       uses: robinraju/release-downloader@v1.7
       with:
        latest: true
        fileName: "source_with_libs.zip"
    
  upload:
    needs: download
    runs-on: ubuntu-latest
    steps:
     - name: download CLI
       run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
     - name: unzip CLI
       run: unzip awscliv2.zip
     - name: install CLI
       run: sudo ./aws/install --update
     - name: configuring CLI
       run: |
           aws configure set region ${{ secrets.AWS_REGION }}
           aws configure set aws_access_key_id ${{ secrets.AWS_KEY }}
           aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
           aws configure set output json
     - name: upload to s3
       run: ls
       run: aws s3 cp ./source_with_libs.zip s3://${{ secrets.BUCKET }}/source_with_libs.zip

